create table if not exists public.reference_time_events (
  id bigint generated by default as identity primary key,
  action_type text not null,
  reference_time timestamptz not null,
  local_reference_time text not null,
  day_type text not null,
  source text not null default 'web',
  created_at timestamptz not null default now()
);

alter table public.reference_time_events enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'reference_time_events'
      and policyname = 'allow anon insert'
  ) then
    create policy "allow anon insert"
      on public.reference_time_events
      for insert
      to anon
      with check (true);
  end if;
end $$;
